[project]
name = "bbochat"
version = "0.1.0"
description = "Chat manager for BBO"
authors = [{name = "Jeff", "email" = "<jeffwatkins2000@gmail.com>"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "appdirs>=1.4.4",
    "bidict>=0.23.1",
    "clipboard>=0.0.4",
    "emoji>=2.14.1",
    "enums>=0.0.2",
    "icecream>=2.1.4",
    "markdown>=3.8",
    "psi-toml>=0.0.18",
    "psiconfig>=0.0.15",
    "psiutils>=0.2.33",
    "pygobject>=3.54.2",
    "python-dateutil>=2.9.0.post0",
    "ruff>=0.15.15",
    "structlog>=25.4.0",
    "tkinterweb>=4.4.4",
    "userpaths>=0.1.3",
]

[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "B", "UP"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
disallow_untyped_defs = true

[build-system]
requires = ['uv-build']
build-backend = 'uv_build'
